spring.application.name=order-management-service

order.service.url=http://localhost:8081/api/v1

customer.service.url=http://localhost:8080/api/v1

banxico.service.url=https://www.banxico.org.mx/SieAPIRest/service/v1

banxico.service.token=41ba58fee99c3889fdf2f6015171530ca9901105bd5ce6a6200217546aa104f2

server.port=8082