spring.application.name=gateway-service
server.port=8085

spring.cloud.gateway.routes[0].id=order-management
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/order-management/**

logging.level.org.springframework.cloud.gateway=DEBUG